#!/bin/bash

set -eu

# Install common hooks
if [ -d $1/etc/initramfs-tools/hooks ] ; then
   cp ../initramfs-tools/hooks/* $1/etc/initramfs-tools/hooks
fi

# Always make sure all initramfs are updated
if [ -s $1/etc/initramfs-tools/update-initramfs.conf ] ; then
   cp $1/etc/initramfs-tools/update-initramfs.conf $1/etc/initramfs-tools/update-initramfs.conf.bak
   sed -i 's/^update_initramfs=.*/update_initramfs=all/' $1/etc/initramfs-tools/update-initramfs.conf
   chroot $1 update-initramfs -u
   mv -f $1/etc/initramfs-tools/update-initramfs.conf.bak $1/etc/initramfs-tools/update-initramfs.conf
fi
