# Inherit all settings from this file, overriding relevant ones for this example.
# Installing additional packages may require increasing system_part_size.
include:
  file: trixie-minbase-ab.yaml

device:
  # This will set the name of the device in Raspberry Pi Connect
  hostname: ota-device-1

artefact:
  version: 1.0.0

image:
  name: myapp

layer:
  app: example-ota
