PKG_NAME := genimage
GENIMAGE_VER ?= 20
PKG_VER := $(GENIMAGE_VER)
PKG_BUILD_SCHEME := autotools
PKG_DEPS := libconfuse
PKG_CONFIGURE_OPTS := --disable-static --disable-dependency-tracking
include ../shared/pkg.mk
