#!/bin/sh

set -eu

# Validate provision map exists
pmap="${IGconf_image_assetdir:-}/device/provisionmap-${IGconf_image_pmap:-}.json"
[ -f "$pmap" ] || die "No pmap. Unable to provision image."


# Generate pre-defined UUIDs
BOOT_LABEL=$(uuidgen | sed 's/-.*//' | tr 'a-f' 'A-F')
BOOT_UUID=$(echo "$BOOT_LABEL" | sed 's/^\(....\)\(....\)$/\1-\2/')
SYSTEM_UUID=$(uuidgen)
CRYPT_UUID=$(uuidgen)
VERITY_UUID=$(uuidgen)

rm -f ${IGconf_image_outputdir}/img_uuids
for v in BOOT_LABEL BOOT_UUID SYSTEM_UUID CRYPT_UUID VERITY_UUID; do
    eval "val=\$$v"
    echo "$v=$val" >> "${IGconf_image_outputdir}/img_uuids"
done


# Install provision map and populate UUIDs
env BOOT_UUID="$BOOT_UUID" SYSTEM_UUID="$SYSTEM_UUID" CRYPT_UUID="$CRYPT_UUID" \
    envsubst '${BOOT_UUID} ${SYSTEM_UUID} ${CRYPT_UUID}' < "$pmap" > "${IGconf_image_outputdir}/provisionmap.json"


# Generate slot map. IDP does preserve GPT labels but this has yet make it to
# mainline. Add the map as a fallback so a provisioned image boots.
pmap --schema "$IGconf_image_pmap_schema" \
     --file "${IGconf_image_outputdir}/provisionmap.json" \
     --slotvars > "$1/boot/slot.map"
