/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docsSidebar: [
    {
      type: 'doc',
      id: 'index',
      label: 'Overview',
    },
    {
      type: 'doc',
      id: 'execution/index',
      label: 'Execution',
    },
    {
      type: 'doc',
      id: 'config/index',
      label: 'Configuration',
    },
    {
      type: 'category',
      label: 'Layers',
      link: {
        type: 'doc',
        id: 'layer/index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'layer',
        },
      ],
    },
    {
      type: 'category',
      label: 'Schemas',
      items: [
        {
          type: 'autogenerated',
          dirName: 'schemas',
        },
      ],
    },
    {
      type: 'doc',
      id: 'provisioning/index',
      label: 'Provisioning',
    },
  ],
};

export default sidebars;
